/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AirDrawRouteImport } from './routes/air-draw'
import { Route as CommandRouteImport } from './routes/command'
import { Route as DualHandRouteImport } from './routes/dual-hand'
import { Route as ExperimentsRouteImport } from './routes/experiments'
import { Route as FaceRouteImport } from './routes/face'
import { Route as GesturesRouteImport } from './routes/gestures'
import { Route as LabRouteImport } from './routes/lab'
import { Route as SessionRouteImport } from './routes/session'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SpaceRouteImport } from './routes/space'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AirDrawRoute = AirDrawRouteImport.update({
  id: '/air-draw',
  path: '/air-draw',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const DualHandRoute = DualHandRouteImport.update({
  id: '/dual-hand',
  path: '/dual-hand',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsRoute = ExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const FaceRoute = FaceRouteImport.update({
  id: '/face',
  path: '/face',
  getParentRoute: () => rootRouteImport,
} as any)
const GesturesRoute = GesturesRouteImport.update({
  id: '/gestures',
  path: '/gestures',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceRoute = SpaceRouteImport.update({
  id: '/space',
  path: '/space',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/air-draw': typeof AirDrawRoute
  '/command': typeof CommandRoute
  '/dual-hand': typeof DualHandRoute
  '/experiments': typeof ExperimentsRoute
  '/face': typeof FaceRoute
  '/gestures': typeof GesturesRoute
  '/lab': typeof LabRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/space': typeof SpaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/air-draw': typeof AirDrawRoute
  '/command': typeof CommandRoute
  '/dual-hand': typeof DualHandRoute
  '/experiments': typeof ExperimentsRoute
  '/face': typeof FaceRoute
  '/gestures': typeof GesturesRoute
  '/lab': typeof LabRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/space': typeof SpaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/air-draw': typeof AirDrawRoute
  '/command': typeof CommandRoute
  '/dual-hand': typeof DualHandRoute
  '/experiments': typeof ExperimentsRoute
  '/face': typeof FaceRoute
  '/gestures': typeof GesturesRoute
  '/lab': typeof LabRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/space': typeof SpaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/air-draw'
    | '/command'
    | '/dual-hand'
    | '/experiments'
    | '/face'
    | '/gestures'
    | '/lab'
    | '/session'
    | '/settings'
    | '/space'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/air-draw'
    | '/command'
    | '/dual-hand'
    | '/experiments'
    | '/face'
    | '/gestures'
    | '/lab'
    | '/session'
    | '/settings'
    | '/space'
  id:
    | '__root__'
    | '/'
    | '/air-draw'
    | '/command'
    | '/dual-hand'
    | '/experiments'
    | '/face'
    | '/gestures'
    | '/lab'
    | '/session'
    | '/settings'
    | '/space'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AirDrawRoute: typeof AirDrawRoute
  CommandRoute: typeof CommandRoute
  DualHandRoute: typeof DualHandRoute
  ExperimentsRoute: typeof ExperimentsRoute
  FaceRoute: typeof FaceRoute
  GesturesRoute: typeof GesturesRoute
  LabRoute: typeof LabRoute
  SessionRoute: typeof SessionRoute
  SettingsRoute: typeof SettingsRoute
  SpaceRoute: typeof SpaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/air-draw': {
      id: '/air-draw'
      path: '/air-draw'
      fullPath: '/air-draw'
      preLoaderRoute: typeof AirDrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dual-hand': {
      id: '/dual-hand'
      path: '/dual-hand'
      fullPath: '/dual-hand'
      preLoaderRoute: typeof DualHandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments': {
      id: '/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof ExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/face': {
      id: '/face'
      path: '/face'
      fullPath: '/face'
      preLoaderRoute: typeof FaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestures': {
      id: '/gestures'
      path: '/gestures'
      fullPath: '/gestures'
      preLoaderRoute: typeof GesturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/space': {
      id: '/space'
      path: '/space'
      fullPath: '/space'
      preLoaderRoute: typeof SpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AirDrawRoute: AirDrawRoute,
  CommandRoute: CommandRoute,
  DualHandRoute: DualHandRoute,
  ExperimentsRoute: ExperimentsRoute,
  FaceRoute: FaceRoute,
  GesturesRoute: GesturesRoute,
  LabRoute: LabRoute,
  SessionRoute: SessionRoute,
  SettingsRoute: SettingsRoute,
  SpaceRoute: SpaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
